version: '3.8'
services:
  lumi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LUMI_MYSQL_DSN
      - LUMI_MONGO_DSN
      - LUMI_MONGO_DB
      - LUMI_MONGO_LOG_DB
    env_file:
      - .env
    ports:
      - "3000:3000"
#    volumes:
#      - ./data:/app/data
    restart: no
